### ISSUE TITLE
Maintain `send_action` interface

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/py-skygear#124]
Follow up https://github.com/SkygearIO/py-skygear/pull/123

We will need to maintain it, since various plugin depends on it.

Probably auto init a container base on current `options` will work?

**Comment by b123400** [comment]
Sorry I don't understand what do you mean by "maintain" an interface, can you elaborate more? Maybe with example why it is not good enough now?

**Comment by rickmak** [comment]
I am referring to this: https://github.com/SkygearIO/py-skygear/pull/123/files#diff-12c0066b27ee4d5374ef3ac153de25dfL30

There is user using the `send_action` without init the Container.

**Comment by b123400** [comment]
I see, ok, will implement
