### ISSUE TITLE
py-skygear should not serve asset if ENVVAR `SERVE_STATIC_ASSETS=false`

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/py-skygear#137]
#### Command to run

```SERVE_STATIC_ASSETS=false py-skygear ```

- Skygear Server Date/Version: 0.22., 20 Apr 2017
- Application Platform: py-skygear

#### Expected Results

SERVE_STATIC_ASSETS will be false and plugin will serve no static asset

#### Actual Results

At `ConfigArgParse==0.10.0`

py-skygear: error: SERVE_STATIC_ASSETS is a flag but is being set to 'false'

If we upgrade `ConfigArgParse==0.11.0`, there will no error. However, SERVE_STATIC_ASSETS will be true even it is `SERVE_STATIC_ASSETS=false`. Only missing of ENVVAR will make the setting to be `False`

Probably need to fix on `ConfigArgParse`, or avoid using `store_true` or `store_false`.

**Comment by cheungpat** [comment]
Upstream issue https://github.com/bw2/ConfigArgParse/issues/87

**Comment by cheungpat** [comment]
Problem fixed in dependency. We will the update dependencies when they made a new release in pypi.
