### ISSUE TITLE
Not able to get record parameters in after save cloud function

### ISSUE THREAD

**Issue by priyankaNav** [SkygearIO/py-skygear#161]
In the Code below am trying to read a record after save. Ideally the "record" should contain all the data that is been saved in previous step, but when i try to get record information i get none for all the fields except username.

@skygear.after_save('user', async=True)
def update_user(record, original_record, db):
	if original_record is None:
		print( record.get("updatedBy"))
		print( record.get("ownerId"))
		print( record.get("createdBy"))
		r = requests.post("https://d3125f95.ngrok.io/insertuser", headers={ "Content-Type": "application/json" }, 
		data=json.dumps({ "username": str(record.get("username")), "_id": str(record.get("_id") )}))
		print(r.text)
	return r

- Skygear Server Date/Version: V1.1.1
- Application Platform:  ubuntu14.04
- [ ] Is this a regression? NO
- [ ] Attached logs, screenshots
![image](https://user-images.githubusercontent.com/17573709/30803663-19f86c0c-a208-11e7-845a-9d399362300f.png)

#### Expected Results
e1fdce23-cc21-4012-806c-3a31fa97cf2b
e1fdce23-cc21-4012-806c-3a31fa97cf2b
e1fdce23-cc21-4012-806c-3a31fa97cf2b
efsdf
#### Actual Results
None
None
None
efsdf
#### Steps to reproduce
1. Add a Before save cloud function and after save cloud function in plugin.py of [`Py-skygear`](https://github.com/SkygearIO/py-skygear)
2. Login/signup from JS template configured with BaaS

**Comment by chpapa** [comment]
Answered at https://discuss.skygear.io/t/not-able-to-get-record-parameters-in-after-save-cloud-function/28/4
