### ISSUE TITLE
Only one handler is registered if two with the same endpoint but different request method is defined

### ISSUE THREAD

**Issue by josephchow102** [SkygearIO/py-skygear#164]
In my case, I implemented handlers `POST` and `PATCH` separately for RESTful API.

However, only one of them is registered and "Route unmatched" error is returned when I send a request with another method type.

**Comment by cheungpat** [comment]
@josephchow102 Can you include the decorator? Thanks.

**Comment by josephchow102** [comment]
```python
@skygear.handler('poll', method=['PATCH'], user_required=True)
@skygear.handler('poll', method=['POST'], user_required=True)
```
