### ISSUE TITLE
pip outdated

### ISSUE THREAD

**Issue by hidden-dimensions** [SkygearIO/py-skygear#192]
When doing docker-compose build on `skygeario/py-skygear:latest` or  `skygeario/skygear-server:v1.3.2` image, we get this warning:
```
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

- Skygear Server Date/Version: 1.3.2
- Application Platform:
- [ ] Is this a regression?
- [x] Attached logs, screenshots

#### Steps to reproduce

1. reset docker (or delete relevant images)
2. `docker-compose build` base on the above images

**Comment by cheungpat** [comment]
thanks! probably we should do a `pip install --upgrade` in the Dockerfile

**Comment by cheungpat** [comment]
Ooh! Turns out we run `pip install --upgrade pip` as part of our image build process. That means the pip in the image is whatever pip version when the image is built. If you need a new version, you can do this in your `Dockerfile`:

```
FROM quay.io/skygeario/py-skygear:onbuild

RUN pip install --upgrade pip
```

**Comment by carmenlau** [comment]
@hidden-dimensions Please find @cheungpat 's comments. In case you want to make sure the pip is the most updated one, you could do it in your `Dockerfile` :)
