### ISSUE TITLE
Database Hooks param `async` is reserved word in Python 3.7

### ISSUE THREAD

**Issue by kitmoovup** [SkygearIO/py-skygear#196]
We found that when we use `pylama` to check the code style. It gives the following warning

```
W606 'async' and 'await' are reserved keywords starting with Python 3.7 [pycodestyle]
```

But one of the params in Database Hooks is `async`. Just want to report the founding and it may cause problem in the future.

**Comment by cheungpat** [comment]
Thanks! I was going to create this issue and you beat me to it 👍

**Comment by cheungpat** [comment]
@carmenlau I think it is possible to make this backward compatible and I would like to tackle on this problem which is affecting my other issues.
