### ISSUE TITLE
Plugin need callback when plugin finish initializing

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/py-skygear#28]
Plugin does not start on its own and py-skygear calls plugin code, but there is no way for a plugin developer to run a function when the plugin program starts.

Need something like this so that `my_init_function` is called after the plugin starts.

```
@after_start
def my_init_function():
  container.send_action("some:action")
```

**Comment by rickmak** [comment]
Another idea is to support `@reboot` syntax on crontab. It take less time to implement as it is extend of existing crontab syntax.

Example:

```
@skygear.every("@reboot")
def my_init_function():
    container.send_action("some:action")
```

**Comment by cheungpat** [comment]
I would say it is only causing less time to implement because we don’t need to add another the verb to the plugin protocol transport

**Comment by cheungpat** [comment]
@rickmak Are we talking about `@reboot` literally or should we think of a better name? I know `@reboot` conforms with [crontab(5)](http://man7.org/linux/man-pages/man5/crontab.5.html) but “reboot” doesn’t mean a thing in skygear-server.

**Comment by rickmak** [comment]
After discussion, this issue will confine to 'call back to plugin after skygear is accepting connection'. Which it not same with process `init`. And only one plugin instance of the same type will got the call if multiple instance is connected.

The intended use case will be db init and migration.

**Comment by rickmak** [comment]
We will try to do two set of API. One is declarative on DB schema and the program will try to make the Db compile with it. Another one is imperative one that will make describe what migration is needed.

**Comment by cheungpat** [comment]
re-assigning this issue to @rickmak since he will be making code to demonstrate how this will work

**Comment by rickmak** [comment]
https://gist.github.com/rickmak/51aa9c4cd438ab3a8c322beb0ccb73fe
I did some developer interview with the above two type of specification style.

declarative:
    - Simple, enough for common case. i.e. just to ensure the column exist for
    after_save
    - Syntaxical prevent removal column away from avrage user.
    - Problem: migration order? there will be `ref`. There can be circular
    reference too.

imperative:
    - Pythonic, explicity know what I am doing
    - Can handle versioning. (Possible, may not nice)
    - Possible to rename column and remove
    - Possible to execute arbitrarily SQL for data migration if needed. For
    example, pre-create row for each user. 


Idea:
    - Can skygear read declarative SQLAlchemy to do the schema migration?

**Comment by royuen** [comment]
Will create concrete tasks after https://github.com/SkygearIO/py-skygear/issues/79
