### ISSUE TITLE
Http handler unable to handle Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/py-skygear#46]
I am trying to setup slack slash command, with skygear plugin http handler.

The request from slack would be a POST request, with `content-type` be `application/x-www-form-urlencoded`, and body be something like this
```
token=gIkuvaNzQIHg97ATvDxqgjtO
team_id=T0001
team_domain=example
channel_id=C2147483705
channel_name=test
user_id=U2147483697
user_name=Steve
command=/weather
text=94070
response_url=https://hooks.slack.com/commands/1234/5678
```

Then I get error response on slack.
```
{"error":{"name":"BadRequest","code":107,"message":"invalid character 'o' in literal true (expecting 'r')"}}
```

My cloud code is something like this
```
@skygear.handler('qwerty', method=['POST'])
def qwerty(request):
    import pprint
    pprint.pprint(request)

    if request.get('token', None) is not 'abcdef':
        return None

    username = request.get('user_name', None)
    text = request.get('text', None)
    response_url = request.get('response_url')

    return 'I got, username: `%s`, text: `%s`' % (username, text)
```

And I cannot see any any console log on portal.

- Skygear Server Date/Version: Portal
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

**Comment by cheungpat** [comment]
I think this is because the handler is not already registered?

**Comment by cheungpat** [comment]
Closing. Although the response is cryptic, the plugin behave as expected (handler was not registered).
