### ISSUE TITLE
Unable to setup pubsub, following skygear-doc

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/py-skygear#47]
from skygear doc

```
from skygear.container import SkygearContainer

container = SkygearContainer()
pubsub = container.pubsub()
```

- Skygear Server Date/Version:
- Application Platform:
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

**Comment by cheungpat** [comment]
reopened as skygeario/skygear-doc#297
