### ISSUE TITLE
Lambda function reserved names

### ISSUE THREAD

**Issue by bensonby** [SkygearIO/py-skygear#89]
The below lambda function will cause an error.

```
@skygear.op('reset-password')
def my_func():
    pass
```

Server response:

```
<!DOCTYPE html>
<p>User not found or code is invalid.</p>
```

The error will be gone by changing `reset-password` to `reset-password2`.
Is there a list of reserved "lambda endpoints" that we should avoid?

**Comment by cheungpat** [comment]
There is not a list of reserved names, but `reset-password` is also [used by the forgot password plugin](https://github.com/SkygearIO/forgot_password/blob/0a76b2392934a46f3f73b95995f49657a179ece7/forgot_password/handlers.py#L147).

Lambda with the same name is able to override another lambda of the same name. However a lambda will not be able to override a handler of the same name.

**Comment by bensonby** [comment]
Thanks @cheungpat.

This will be addressed through skygear doc in the cloud code section
