### ISSUE TITLE
`skygear.skyconfig.config` is empty if the plugin is restarted and don't go through init process

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/py-skygear#99]
Expecting `skygear.skyconfig.config` behave consistently. Or just force user to use `skygear.options`

- Skygear Server Date/Version: 0.19.1
- Application Platform: py-skygear
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results
The configuration of skygear-server

#### Actual Results

```
skygear.skyconfig.config.app.api_key
AttributeError: 'Configuration' object has no attribute 'app'
```

#### Steps to reproduce

1. Open the skygear-server
2. Connect the plugin to skygear-server to go through the init process.
3. Read from the config -> ok
4. restart the plugin
5. Read from the config -> fails.

**Comment by ben181231** [comment]
The `skygear.skyconfig.config` will only exists within init event.
